### PR TITLE
Export FormatDurationOptions

### PR DESCRIPTION
**Pull request by sebinemeth**
Export FormatDurationOptions for advanced TypeScript usage

### CODE REVIEW

**Review by SGarcia710 — APPROVED** [review]

**Comment by SGarcia710** [comment]
upvote

**Comment by sebinemeth** [comment]
@ungoldman any chance you can review this? Thanks!

**Comment by ungoldman** [comment]
Hi folks, sorry to keep you hanging on this issue. Is there anything extra that needs to be configured in package.json for this to work for you, or is the added `export` in this file sufficient for a minor release?

**Comment by sebinemeth** [comment]
Hi, it worked with the provided changes, no other changes were needed. However, I did not perform thorough testing.

**Comment by ungoldman** [comment]
Will add it to next minor release

**Comment by ungoldman** [comment]
shipped in [3.0.0](https://github.com/ungoldman/format-duration/releases/tag/v3.0.0)

**Pull request merged**
