### PR TITLE
Leading zeros

### PR DESCRIPTION
**Pull request by Deseteral**
This PR adds support for `leadingZeros` option flag. It might be useful formatting option.

Example:
```javascript
format(1000 * 60 - 1) // '0:59'
format(1000 * 60 - 1, { leadingZeros: true }) // '00:59'
```

Let me know what you think 😄

### CODE REVIEW

**Comment by ungoldman** [comment]
Hi @Deseteral, thanks for the PR! Looks okay to me, please remove the `package-lock.json` file though :)

**Comment by ungoldman** [comment]
also might want to shorten the option to just `leading`

**Comment by Deseteral** [comment]
Why should I remove `package-lock.json`? It's intended to be commited.

**Comment by ungoldman** [comment]
@Deseteral no, it isn't :)

`package-lock.json` makes sense for some projects where you want to lock the versions of top-level and transitive dependencies. But not for modules.

Importantly, when `npm` is resolving dependencies, it does NOT respect the `package-lock.json` of modules it installs.

From the documentation:

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

https://docs.npmjs.com/files/package-lock.json

So generally a lot of module authors avoid committing `package-lock.json` to their repositories because it can often provide false data.

For example, a bug might be undetectable because modules in `package-lock.json` are locked at the repo level, but when the module is in use, one of its dependencies has introduced a breaking change that breaks the module for users.

So, for these many reasons, please remove `package-lock.json`. Thank you!

I will also add `package-lock.json` to `.gitignore` for this project so this issue is less confusing for contributors in the future.

**Comment by Deseteral** [comment]
Interesting. I didn't know that. Thanks for the explanation 😄 
`package-lock.json` is now removed and I've changed the name of `leadingZeros` option to just `leading`.

Let me know what do you think about it now 😃

**Comment by ungoldman** [comment]
Released in [`1.3.0`](https://github.com/ungoldman/format-duration/releases/tag/v1.3.0) 🚀

**Comment by ungoldman** [comment]
One final note -- just transferred ownership of this project to https://github.com/hypermodules to share maintenance.

**Pull request merged**
